#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 27 22:41:14 2018

@author: christinamooshil

Examining Mandelbrot Set
"""

import numpy as np
import matplotlib.pyplot as plt

def testpoint(z, maxreps):
    reps = 0
    #w = complex(0.3,-0.01) 
    w = complex(-0.79,0.15)
    #w = complex(0.28,0.008) 
    while abs(z) < 2 and reps < maxreps:
        z = z ** 2 + w
        reps += 1
    #frac = float(reps) / float(maxreps)
    #return frac
    return reps

def compute_mandelbrot(N_max, xmin, xmax, ymin, ymax, nx, ny):
    # A grid of c-values
    x = np.linspace(xmin, xmax, nx)
    y = np.linspace(ymax, ymin, ny)
    z = np.zeros([nx, ny])
    for a in range(nx):
        for b in range(ny):
            z[a, b]=testpoint(complex(x[a], y[b]), N_max)
    #print(z)  
    return z

def main(): 
    #zoomed image
#    xmin = -1
#    xmax = -0.5
#    ymin = 0
#    ymax = 0.5
    #whole image
#    xmin = -1.5
#    xmax = 1.5
#    ymin = -1
#    ymax = 1
    
    maxNumSteps = 264
    pts = 600
#    mandelbrot_set = compute_mandelbrot(maxNumSteps, xmin, xmax, ymin, ymax, pts, pts)
    xexampt = float(input('Enter an x value to examine: '))
    yexampt = float(input('Enter a y value to examine: '))
    diam = float(input('Enter a diameter to examine: '))
    
    m = compute_mandelbrot(maxNumSteps, xexampt - diam/2, xexampt + diam/2, yexampt - diam/2, yexampt + diam/2, pts, pts)
    plt.imshow(m.T, extent=[xexampt - diam/2, xexampt + diam/2, yexampt - diam/2, yexampt + diam/2], cmap = plt.cm.rainbow)
    plt.colorbar()
    # Save
    filename = 'mandelbrot-'+str(maxNumSteps) + '-' + str(pts)+'.pdf'
    plt.savefig(filename, format = 'pdf')
    
main()