#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 21 16:22:11 2018

@author: christinamooshil
"""

"""
Compute the Mandelbrot fractal
"""


import numpy as np
import matplotlib.pyplot as plt

def testpoint(z, maxreps):
    reps = 0
    w = complex(-0.70176,-0.3842)
    while abs(z) < 2 and reps < maxreps:
        z = z ** 2 + w
        reps += 1
    return reps

def compute_mandelbrot(N_max, xmin, xmax, ymin, ymax, nx, ny):
    # A grid of c-values
    x = np.linspace(xmin, xmax, nx)
    y = np.linspace(ymax, ymin, ny)
    z = np.zeros([nx, ny])
    for a in range(nx):
        for b in range(ny):
            z[a, b]=testpoint(complex(x[a], y[b]), N_max) 
    return z

def main(): 
    #zoomed image
#    xmin = -1
#    xmax = -0.5
#    ymin = 0
#    ymax = 0.5
    #whole image
    xmin = -1.5
    xmax = 1.5
    ymin = -1
    ymax = 1
    
    maxNumSteps = 264
    pts = 600
    mandelbrot_set = compute_mandelbrot(maxNumSteps, xmin, xmax, ymin, ymax, pts, pts)
    
    plt.imshow(mandelbrot_set.T, extent=[xmin, xmax, ymin,ymax], cmap = plt.cm.rainbow)
    plt.colorbar()
    # Save
    filename = 'mandelbrot-'+str(maxNumSteps) + '-' + str(pts)+'.pdf'
    plt.savefig(filename, format = 'pdf')
    
main()